//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flyingcap.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        public int id { get; set; }
        public string CLASSNAME { get; set; }
        public string CLASSLEVEL { get; set; }
        public string LOCATION { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string SESSIONDURATION { get; set; }
        public string ABOUTCLASS { get; set; }
        public byte[] CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public string TYPECLASS { get; set; }
    }
}
