//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flyingcap.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTNER
    {
        public int ID { get; set; }
        public string SCHOOLNAME { get; set; }
        public string SCHOOLIMAGE { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> CLASSID { get; set; }
        public string CLASSNAME { get; set; }
        public string CLASSLEVEL { get; set; }
        public string LOCATION { get; set; }
    }
}
